project_name: opentelemetry-collector-releases
builds:
    - id: otelcol-contrib
      goos:
        - darwin
        - linux
      goarch:
        - amd64
        - arm64
      goarm:
        - "7"
      dir: distributions/otelcol-contrib/_build
      binary: otelcol-contrib
      ldflags:
        - -s
        - -w
      flags:
        - -trimpath
      env:
        - CGO_ENABLED=0
archives:
    - id: otelcol-contrib
      builds:
        - otelcol-contrib
      name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}'
checksum:
    name_template: '{{ .ProjectName }}_checksums.txt'
dockers:
    - goos: linux
      goarch: amd64
      dockerfile: distributions/otelcol-contrib/Dockerfile
      image_templates:
        - otel/opentelemetry-collector-contrib:{{ .Version }}-amd64
        - otel/opentelemetry-collector-contrib:latest-amd64
      extra_files:
        - configs/otelcol-contrib.yaml
      build_flag_templates:
        - --pull
        - --platform=linux/amd64
        - --label=org.opencontainers.image.created={{.Date}}
        - --label=org.opencontainers.image.name={{.ProjectName}}
        - --label=org.opencontainers.image.revision={{.FullCommit}}
        - --label=org.opencontainers.image.version={{.Version}}
        - --label=org.opencontainers.image.source={{.GitURL}}
      use: buildx
docker_manifests:
    - name_template: otel/opentelemetry-collector-contrib:{{ .Version }}
      image_templates:
        - otel/opentelemetry-collector-contrib:{{ .Version }}-amd64
    - name_template: otel/opentelemetry-collector-contrib:latest
      image_templates:
        - otel/opentelemetry-collector-contrib:latest-amd64
